name: 'Translation Action'
description: 'Automatically sync and review translations across repositories'
author: 'QuantEcon'

branding:
  icon: 'globe'
  color: 'blue'

inputs:
  # Mode selection
  mode:
    description: 'Operation mode: sync (create translation PRs) or review (quality assessment)'
    required: true
  
  # Sync mode inputs
  target-repo:
    description: 'Target repository for translations (owner/repo). Required for sync mode.'
    required: false
  target-language:
    description: 'Target language code (e.g., zh-cn, fa). Required for sync mode.'
    required: false
  
  # Review mode inputs
  source-repo:
    description: 'Source repository for English content (owner/repo). Required for review mode.'
    required: false
  max-suggestions:
    description: 'Maximum number of improvement suggestions in review comment'
    required: false
    default: '5'
  
  # Shared inputs
  docs-folder:
    description: 'Documentation folder pattern (e.g., lectures/)'
    required: false
    default: 'lectures/'
  source-language:
    description: 'Source language code (e.g., en)'
    required: false
    default: 'en'
  glossary-path:
    description: 'Path to custom translation glossary JSON file (optional - built-in glossary used by default)'
    required: false
    default: ''
  toc-file:
    description: 'Table of contents file name'
    required: false
    default: '_toc.yml'
  anthropic-api-key:
    description: 'Anthropic API key for Claude'
    required: true
  claude-model:
    description: 'Claude model to use for translation'
    required: false
    default: 'claude-sonnet-4-5-20250929'
  github-token:
    description: 'GitHub token for API access'
    required: true
  pr-labels:
    description: 'Comma-separated labels for created PRs'
    required: false
    default: 'action-translation,automated'
  pr-reviewers:
    description: 'Comma-separated list of GitHub usernames to request as reviewers (e.g., user1,user2). Leave empty for no reviewers.'
    required: false
    default: ''
  pr-team-reviewers:
    description: 'Comma-separated list of GitHub team slugs to request as reviewers (e.g., team1,team2). Leave empty for no team reviewers.'
    required: false
    default: ''
  test-mode:
    description: 'Run in test mode (use PR head commit instead of merge commit). Set to "true" for testing.'
    required: false
    default: 'false'

outputs:
  # Sync mode outputs
  pr-url:
    description: 'URL of the created pull request (sync mode)'
  files-synced:
    description: 'Number of files synchronized (sync mode)'
  
  # Review mode outputs
  review-verdict:
    description: 'Review verdict: PASS, WARN, or FAIL (review mode)'
  translation-score:
    description: 'Overall translation quality score 1-10 (review mode)'
  diff-score:
    description: 'Diff quality score 1-10 (review mode)'

runs:
  using: 'node20'
  main: 'dist/index.js'
